version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: lofoten_backend
    restart: unless-stopped
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/data.db:/app/data.db
      - ./ImageStorage:/ImageStorage
      - ./GpxStorage:/GpxStorage
    networks:
      - lofoten_net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: lofoten_frontend
    restart: unless-stopped
    ports:
      - "127.0.0.1:5567:80"
    depends_on:
      - backend
    networks:
      - lofoten_net

networks:
  lofoten_net:
    driver: bridge
